export const DEFAULT_SETTINGS = {
  CODEX_MEM_MODEL: 'gpt-5',
  CODEX_MEM_CONTEXT_OBSERVATIONS: '50',
  CODEX_MEM_WORKER_PORT: '37777',
  CODEX_MEM_WORKER_HOST: '127.0.0.1',

  CODEX_MEM_PROVIDER: 'codex',
  CODEX_MEM_GEMINI_API_KEY: '',
  CODEX_MEM_GEMINI_MODEL: 'gemini-2.5-flash-lite',
  CODEX_MEM_OPENROUTER_API_KEY: '',
  CODEX_MEM_OPENROUTER_MODEL: 'xiaomi/mimo-v2-flash:free',
  CODEX_MEM_OPENROUTER_SITE_URL: '',
  CODEX_MEM_OPENROUTER_APP_NAME: 'codex-mem',
  CODEX_MEM_GEMINI_RATE_LIMITING_ENABLED: 'true',

  CODEX_MEM_CONTEXT_SHOW_READ_TOKENS: 'false',
  CODEX_MEM_CONTEXT_SHOW_WORK_TOKENS: 'false',
  CODEX_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT: 'false',
  CODEX_MEM_CONTEXT_SHOW_SAVINGS_PERCENT: 'true',

  CODEX_MEM_CONTEXT_FULL_COUNT: '0',
  CODEX_MEM_CONTEXT_FULL_FIELD: 'narrative',
  CODEX_MEM_CONTEXT_SESSION_COUNT: '10',

  CODEX_MEM_CONTEXT_SHOW_LAST_SUMMARY: 'true',
  CODEX_MEM_CONTEXT_SHOW_LAST_MESSAGE: 'false',

  CODEX_MEM_EXCLUDED_PROJECTS: '',
  CODEX_MEM_FOLDER_MD_EXCLUDE: '[]',
} as const;
